### PR TITLE
Default to using the host specified to serverless-offline

### PR DESCRIPTION
**Pull request by TiVoMaker**
Matthew - take a look. I think this is the cleanest way to do it. I've updated the README to match.

### CODE REVIEW

**Comment by mj1618** [comment]
I like it! Thanks for figuring out how to do it. I agree with the order you've decided on as well - `config.host` should override `options.host`.

Do you mind changing this line though `if not provided to serverless-offline` to `overrides the ones provided by serverless-offline` or something similar?

Also - docker works the same on linux and mac, and any other platform you could run docker on - so we can make the comment non-specific to OSX.

**Comment by mj1618** [comment]
Also just resolve those conflicts before I merge.

Thank you!

**Comment by TiVoMaker** [comment]
No problem. I'll fix up the conflicts and wording. 

On OSX, Docker has a number of problems. On Linux, you're actually running on the same kernel, just through the Xen-derived sandbox, making it very fast. On OSX, it actually runs in a real VM, and networking with the host is done through a complex VPN package (and it's all a bit buggy; Docker put a reset button right in the dropdown menu because you need it so much).

I believe that the 0.0.0.0 host setting works properly in either case, but I don't have a Linux box up and running to test with right now.

**Comment by mj1618** [comment]
Oh ok, I thought they fixed that on OSX with "Docker for Mac". I could be wrong though.

No problem feel free to leave that wording.

**Pull request merged**
