### PR TITLE
Auto-subscribe SQS queues

### PR DESCRIPTION
**Pull request by jagregory**
Hey, I'm looking for feedback on this PR. Is it something that's desirable to have in this plugin? Any advice on how best to implement it?

**What does it do?**

This PR adds the ability to auto-subscribe SQS queues to an SNS topic. This change is particularly useful when combining this plugin with [serverless-offline-sqs](https://www.npmjs.com/package/serverless-offline-sqs), as it means you don't need any additional application code to subscribe your queue to your SNS topic. This is much closer to the reality of AWS's out-of-the-box SNS->SQS integration.

**How it works**

There's an additional (optional) configuration option:

```yaml
  serverless-offline-sns:
    subscriptions:
      - topic: MyTopic
        queue: http://localhost:4576/queue/MyQueue
```

And then on start, just like how functions are subscribed, the plugin iterates that subscriptions list and auto-subscribes any queues.

**Considerations**

- Is this something desirable to have in this plugin?
- How do you feel about the config changes?
- What's the best way to implement this? There's significant overlap between the `subscribe` and `subscribeQueue` functions.
- I know there are no tests, I'll add some when we nail this stuff down :)

### CODE REVIEW

**Comment by mj1618** [comment]
I like it - doesn't interfere much with the current code and is useful. Mind adding it to the readme as well?

**Comment by mj1618** [comment]
Sorry for the late response as well. It does look like a great addition though, with some tests I'd love to merge it in.

**Comment by bitsofinfo** [comment]
@jagregory @mj1618 totally need this as well.. merge status? https://github.com/CoorpAcademy/serverless-plugins/issues/156

**Comment by ignaciogrondona** [comment]
@jagregory @mj1618 I really need this too! 🙏

**Review by mj1618 — DISMISSED** [review]

**Comment by mj1618** [comment]
For reasons of efficiency and the demand for this I'm going to merge this and create an issue to add some tests to this later.

**Comment by mj1618** [comment]
Sorry for the delay everyone :(

**Comment by bitsofinfo** [comment]
is this cut into a release?

**Comment by bitsofinfo** [comment]
is this cut into a release?

**Comment by bitsofinfo** [comment]
@jagregory so I pulled down 0.76.0 which I guess has this baked in... however it doesn't seem to work.

I have an elasticmq running locally w/ a queue in it, listening on 9324 

```
  serverless-offline-sns:
    subscriptions:
      - topic: MyTopic.fifo
        queue: http://localhost:9324/queue/MyQueue 
```

I have my app send some messages to `MyTopic`, but I see zero activity looking in the elasticmq logs.

I do see this however:

```
Serverless: DEBUG[serverless-offline-sns][server]: [{"SubscriptionArn":"arn:aws:sns:us-west-2:123456789012:MyTopic.fifo:316471","Protocol":"sqs","TopicArn":"arn:aws:sns:us-west-2:123456789012:MyTopic.fifo","Endpoint":"http://localhost:9324/queue/MyQueue","Owner":"","Attributes":{}}]
```

**Pull request merged**
