### PR TITLE
Feature/multiple serverless

### PR DESCRIPTION
**Pull request by artem7902**

### CODE REVIEW

**Comment by mj1618** [comment]
Hi there, thank you for submitting, happy to merge but would you mind resolving the merge conflicts?

**Comment by mj1618** [comment]
Also getting an error with shelljs install

**Comment by artem7902** [comment]
@mj1618 Hey, thanks for your attention. I've resolved conflicts, fixed tests and added small docs for this feature,

**Comment by mj1618** [comment]
Amazing thank you Artem! I will review and merge shortly.

**Pull request merged**
