### PR TITLE
Make sure all policies match and test to check this case

### PR DESCRIPTION
**Pull request by mteleskycmp**
This fixes the issue where an event has a matching key for every policy provided, but the values don't match.

For example:

   ```
filterPolicy:
      pet:
        - dog
        - cat
      color:
        - white
```

Events where pet is dog or cat, but no color is provided will successfully be stopped. However, dogs with color black would still make it through.

### CODE REVIEW

**Comment by mteleskycmp** [comment]
Any idea when we can get some eyes on this ? Having to manually edit the package after installing sucks :D

**Comment by mteleskycmp** [comment]
Any idea when I can get a review on this? 😄

**Comment by mteleskycmp** [comment]
Updated the branch with the most recent changes. It has been almost a month since I made this PR, any chance someone could review it soon? it is a very minor change, but it is important for those of us who have multiple fields in our filter policies

**Comment by mj1618** [comment]
@all-contributors please add @mteleskycmp for bugs and code

**Comment by mj1618** [comment]
@all-contributors please add @mteleskycmp for bugs and code

**Comment by mj1618** [comment]
@all-contributors please add @mteleskycmp @perkyguy @victorsferreira for bugs and code

**Comment by mteleskycmp** [comment]
Thanks for merging it in! Appreciate it!

**Pull request merged**
